const money=n=>n.toLocaleString('vi-VN')+'₫';let cart=JSON.parse(localStorage.getItem('luxecar_cart')||'[]');
function save(){localStorage.setItem('luxecar_cart',JSON.stringify(cart));document.querySelectorAll('#cartCount').forEach(e=>e.textContent=cart.reduce((a,x)=>a+x.qty,0))}
function addCart(id){let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,qty:1});save();alert('Đã thêm xe vào giỏ hàng.');}
function card(c){return `<article class="carCard"><a class="carImg" href="./car.html?id=${c.id}" style="background-image:url('${c.img}')"></a><div class="carBody"><small>${c.brand} · ${c.type}</small><h3>${c.name}</h3><div class="price">${money(c.vnd)}</div><p>≈ $${c.usd.toLocaleString('en-US')} MSRP quốc tế</p><div class="cardActions"><a href="./car.html?id=${c.id}">CHI TIẾT</a><button onclick="addCart('${c.id}')">THÊM VÀO GIỎ</button></div></div></article>`}
function renderCatalog(){let grid=document.getElementById('catalogGrid');if(!grid)return;let sel=document.getElementById('brand');[...new Set(CARS.map(c=>c.brand))].sort().forEach(b=>sel.innerHTML+=`<option>${b}</option>`);let draw=()=>{let q=document.getElementById('query').value.toLowerCase(),b=sel.value;grid.innerHTML=CARS.filter(c=>(b==='all'||c.brand===b)&&(`${c.name} ${c.brand} ${c.type}`.toLowerCase().includes(q))).map(card).join('')};document.getElementById('query').oninput=draw;sel.onchange=draw;draw()}
function renderFeatured(){let e=document.getElementById('featured');if(e)e.innerHTML=CARS.slice(0,6).map(card).join('')}
function renderBrands(){let e=document.getElementById('brandGrid');if(!e)return;let brands=[...new Set(CARS.map(c=>c.brand))];e.innerHTML=brands.map(b=>`<a class="brandCard" href="./cars.html?brand=${encodeURIComponent(b)}"><span>${b.slice(0,2).toUpperCase()}</span><h2>${b}</h2><p>${CARS.filter(c=>c.brand===b).length} mẫu xe</p></a>`).join('')}
function removeCart(id){cart=cart.filter(x=>x.id!==id);save();renderCheckout();renderCartUI();}function changeCartQty(id,delta){let x=cart.find(x=>x.id===id);if(!x)return;x.qty=Math.max(1,x.qty+delta);save();renderCheckout();renderCartUI();}function renderCartUI(){const e=document.getElementById('cartItems');if(!e)return;e.innerHTML=cart.map(x=>{const c=CARS.find(c=>c.id===x.id);if(!c)return '';return `<div class="cartItem"><img src="${c.img}" alt="${c.name}"><div class="cartInfo"><a href="./car.html?id=${c.id}"><strong>${c.name}</strong></a><span>${money(c.vnd)}</span><div class="cartControls"><button type="button" onclick="changeCartQty('${c.id}',-1)">−</button><b>${x.qty}</b><button type="button" onclick="changeCartQty('${c.id}',1)">+</button><button type="button" class="cartRemove" onclick="removeCart('${c.id}')">🗑 Xóa</button></div></div></div>`}).join('')||'<p class="emptyCart">Giỏ hàng đang trống.</p>';}function renderCheckout(){let e=document.getElementById('order');if(!e)return;let id=new URLSearchParams(location.search).get('id');if(id&&!cart.find(x=>x.id===id))cart.push({id,qty:1});let rows=cart.map(x=>{let c=CARS.find(c=>c.id===x.id);return `<div class="orderRow"><span>${c.name} × ${x.qty} <button type="button" class="cartRemove" onclick="removeCart('${x.id}')">🗑 Xóa</button></span><b>${money(c.vnd*x.qty)}</b></div>`}).join('');let total=cart.reduce((a,x)=>a+(CARS.find(c=>c.id===x.id)?.vnd||0)*x.qty,0);e.innerHTML=rows||'<p>Chưa có xe trong giỏ.</p>';e.innerHTML+=`<div class="orderTotal"><span>Tổng dự kiến</span><b>${money(total)}</b></div>`;save();renderCartUI();let f=document.getElementById('payForm');if(f)f.onsubmit=async ev=>{ev.preventDefault();const s=window.LuxeAuth&&LuxeAuth.session();if(!s){location.href='./auth.html?return=checkout';return}const inputs=[...f.querySelectorAll('input')];const email=inputs.find(x=>x.type==='email')?.value||s.email;const carName=cart.length?(CARS.find(c=>c.id===cart[0].id)?.name||'Xe'): 'Yêu cầu mua xe';const order={id:crypto.randomUUID(),email,name:inputs[0]?.value||s.name,carName,total,createdAt:new Date().toISOString(),status:'Đã tiếp nhận'};LuxeAuth.saveOrder(order);const api=(window.LUXECAR_CONFIG||{}).API_BASE;if(api){try{const r=await fetch(api+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});if(r.ok){document.getElementById('payMsg').textContent='✓ Đã gửi đơn tới hệ thống LuxeCar. Hệ thống sẽ gửi hướng dẫn thanh toán qua email.';return}}catch(e){}}document.getElementById('payMsg').textContent='✓ Yêu cầu đã lưu. GitHub Pages đang ở chế độ demo; thanh toán thật cần backend/Stripe.'}}
renderFeatured();renderCatalog();renderBrands();renderCheckout();renderCartUI();save();
